### ISSUE TITLE
Bug: expects blank linke when default exporting an object

### ISSUE THREAD

**Issue by simonhaenisch** [chinchiheather/tslint-lines-between-class-members#10]
Using the rule `"lines-between-class-members": [true, 1]`:

```ts
export default {
  foo() {},
}
```

> must have 1 new line(s) between class methods, see docs for how to configure (lines-between-class-members)

Adding a blank line above `foo() {}` "fixes" it, but conflicts with `no-empty-line-after-opening-brace` and it's not really the case that it is "between" class members. This is not even a class, so the rule shouldn't apply anyway.

**Comment by chinchiheather** [comment]
Thanks for raising this @simonhaenisch, I'll start working on a fix for it soon

**Comment by chinchiheather** [comment]
This should be fixed now @simonhaenisch in v1.3.1
