### ISSUE TITLE
fix seem not respect tab size

### ISSUE THREAD

**Issue by canemacchina** [chinchiheather/tslint-lines-between-class-members#15]
After running `tslint --fix`, this is the diff:

```
     }
-    public pause (): void {
+
+  public pause (): void {
```

As you can see, the rule insert two space, and not four
(my tslint.conf have `"indent": [ true, "spaces", 4 ]`)

**Comment by chinchiheather** [comment]
I think this should have been resolved by the fix for #21 - let me know if you still experience this problem after updating to 1.3.4
