### ISSUE TITLE
Disable rule

### ISSUE THREAD

**Issue by lonix1** [chinchiheather/tslint-lines-between-class-members#18]
TSLint allows me to disable rules for "whole file", "next line", or "this line". I assumed this rule could also be disabled.

I tried:

````
// tslint:disable-next-line:lines-between-class-members
````

and

````
// tslint:disable-line:lines-between-class-members
````

Which don't work. Please advise?

**Comment by chinchiheather** [comment]
Hi @lonix1, sorry for the delayed response, can you give me an example of how you are trying to disable it? I tried using
```
/* tslint:disable:lines-between-class-members */
```
and it worked fine, how are doing the next line disable?

**Comment by lonix1** [comment]
I tried the usual ways in the original post, which didn't work unfortunately.

**Comment by chinchiheather** [comment]
I mean an example within your code, so I can see exactly how you are trying to disable it
I can do this to prevent the linting error and it works fine
```js
class App {
  private a = "b";
  // tslint:disable-line:lines-between-class-members
  constructor() {
    this.a = "c";
  }
}
```

**Comment by lonix1** [comment]
That seems to work for me, maybe an update fixed it? Thanks!

**Comment by chinchiheather** [comment]
Awesome! Glad to hear it :)
