### ISSUE TITLE
Complex class declarations

### ISSUE THREAD

**Issue by pburkindine** [chinchiheather/tslint-lines-between-class-members#25]
Ref: https://github.com/chinchiheather/tslint-lines-between-class-members/issues/19

Re-opening as 1.3.2 did not completely fix the issue; please reference https://github.com/chinchiheather/tslint-lines-between-class-members/issues/19#issuecomment-510138015 for examples of scenarios still exhibiting the issue.

**Comment by chinchiheather** [comment]
This should be fixed in 1.3.5, let me know if you still experience any problems
