### ISSUE TITLE
Error if there is a comment above the class

### ISSUE THREAD

**Issue by enessoylu** [chinchiheather/tslint-lines-between-class-members#7]
I am getting an error if there is a comment above the class definition. If I log the previousLine in this case, I see that it calculates the previousLine wrongly. Please look:

![bug](https://user-images.githubusercontent.com/20838344/40160487-76a52e16-59b6-11e8-9bbb-994f577ad14d.gif)

**Comment by chinchiheather** [comment]
Thanks for raising this @enessoylu , also nice screenshot gifs! Really helpful :)
This should now be fixed, I released a new version 1.2.4
